services:
  asir_bind9:
    container_name: asir_bind9
    image: ubuntu/bind9
    platform: linux/amd64
    ports:
      - 53:53
    networks:
      bind9_subnet:
        ipv4_address: 172.28.5.1
    volumes:
      - ./conf:/etc/bind
      - ./zonas:/var/lib/bind

  asir_apache:
    container_name: asir_apache
    image: httpd:latest
    ports:
    - 80:80
    networks:
      bind9_subnet:
        ipv4_address: 172.28.5.13
    volumes:
    - ./paginas:/usr/local/apache2/htdocs
    - ./conf:/usr/local/apache2/conf
    dns:
      - 172.28.5.1
  cliente:
    container_name: cliente
    image: ubuntu
    platform: linux/amd64
    tty: true
    stdin_open: true
    dns:
      - 172.28.5.1
    networks:
      bind9_subnet:
        ipv4_address: 172.28.5.2

networks:
  bind9_subnet:
    external: true